name: Playwright CI Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: # allows manual trigger
  
    schedule: 
    - cron: "0 * * * *"  # runs at the top of every hour
  

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      
      # 1️⃣ Get your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node + cache node_modules
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5️⃣ Run Playwright tests
      - name: Run Playwright Tests
        run: npx playwright test tests/DemoQaLogin.spec.js
        env:
          CI: true

      # 6️⃣ Upload HTML Report
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      # 7️⃣ Upload Videos/Traces/Screenshots
      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

      # 8️⃣ Upload Screenshots folder (optional)
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
